version: '3.9'
services:
  filibustier:
    build:
      context: filibustier
      dockerfile: Dockerfile
    container_name: filibustier
    init: true
    tty: true
    stdin_open: true
    environment:
      - DB_HOST=maria-db
      - DB_PORT
      - PROXY_HOST=proxy
      - PROXY_PORT
      - TELEGRAM_BOT_AUTH_KEY=6862350364:AAG0PDcjuKOgoB6izBNBysaQUNKII8x-QuQ
    depends_on:
      maria-db:
        condition: service_healthy
      proxy:
        condition: service_healthy

  maria-db:
    build:
      context: maria-db
      dockerfile: Dockerfile
      args:
        - MARIADB_ROOT_PASSWORD
        - MARIADB_DATABASE
        - MARIADB_USER
        - MARIADB_PASSWORD
    container_name: maria-db
    init: true
    tty: true
    stdin_open: true
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-prootPassword" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10

  proxy:
      image: osminogin/tor-simple
      container_name: proxy
      restart: always
      stdin_open: true
