version: '3.9'
services:
  filibustier:
    build:
      context: filibustier
      dockerfile: Dockerfile
    container_name: filibustier
    init: true
    tty: true
    stdin_open: true
    environment:
      - DB_HOST
      - DB_PORT
      - PROXY_HOST
      - PROXY_PORT
      - TELEGRAM_BOT_AUTH_KEY
    depends_on:
      maria-db:
        condition: service_healthy
      proxy:
        condition: service_healthy

  db-updater:
    build:
      context: db-updater
      dockerfile: Dockerfile
      args:
        - DB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - DB_HOST
        - DB_NAME=${MARIADB_DATABASE}
    container_name: db-updater
    init: true
    tty: true
    stdin_open: true
    environment:
      - DB_NAME=${MARIADB_DATABASE}
      - DB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - DB_HOST
    depends_on:
      maria-db:
        condition: service_healthy

  maria-db:
    build:
      context: maria-db
      dockerfile: Dockerfile
      args:
        - MARIADB_ROOT_PASSWORD
        - MARIADB_DATABASE
        - MARIADB_USER
        - MARIADB_PASSWORD
    container_name: maria-db
    init: true
    tty: true
    stdin_open: true
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    healthcheck:
      test: [ "CMD", "mariadb-admin", "--password=$MARIADB_ROOT_PASSWORD" ,"ping", "-h", "localhost" ]
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 10

  proxy:
      image: osminogin/tor-simple
      container_name: proxy
      restart: always
      stdin_open: true
