version: '3.9'
services:
  maria-db:
    build:
      context: maria-db
      dockerfile: Dockerfile
      args:
        - MARIADB_ROOT_PASSWORD
        - MARIADB_DATABASE
        - MARIADB_USER
        - MARIADB_PASSWORD
    container_name: maria-db
    init: true
    tty: true
    stdin_open: true
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-prootPassword" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  proxy:
      image: osminogin/tor-simple
      container_name: proxy
      restart: always
      ports:
        - 9050:9050